# Generated by Django 5.0.6 on 2024-07-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_bloodtype_item_btype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='College',
            new_name='Primary',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Vcourse',
            new_name='SssId',
        ),
        migrations.AddField(
            model_name='item',
            name='Tertiary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='TinId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
