# Generated by Django 5.0.6 on 2024-07-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_college_item_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Baranggay',
        ),
    ]
